### ISSUE TITLE
This app is no longer doing what it should do

### ISSUE THREAD

**Issue by Ftonans** [ManeraKai/simplytranslate_mobile#230]
Request are made directy through translate.google.com and not any of SimplyTranslate instances. Requests are not proxified so you are completely exposed to google. You can find it in code [here](https://github.com/ManeraKai/simplytranslate_mobile/blob/main/lib/simplytranslate.dart)

**Comment by ManeraKai** [comment]
if you want to anonymize your IP, use Orbot or a VPN.

**Comment by Ftonans** [comment]
> if you want to anonymize your IP, use Orbot or a VPN.

I know it, but that's not the point and you know about it.

App previously used SimplyTranslate and now it uses GoogleTranslate. You did not make any announcements or warnings. It appears to be malicious behavior that you completely changed the purpose of the app, and people may lose trust (some of them already lost it) in you and your other projects, knowing what you are capable of doing. It is up to you, of course, what you decide to do, but I recommend at least changing the description on [F-Droid](https://f-droid.org/en/packages/com.simplytranslate_mobile/)(it literally says and probably on GitHub too (it's not "Alternative Frontend" anymore)

**Comment by ManeraKai** [comment]
Let me say the change was rapid bc of simple-web.org isn't working and people rushed me, the implementation has some bugs even. I did announce this in the [changelog](https://github.com/ManeraKai/simplytranslate_mobile/releases/tag/v1.4.0). Changing the description and the website are somewhat difficult bc there are translations, that's why I didn't do them yet.

I should release another version fixing the bugs and cleaning the website and description.
