### ISSUE TITLE
Add Text-To-Speech Functionality

### ISSUE THREAD

**Issue by metalune1** [ManeraKai/simplytranslate_mobile#88]
Hi, as of today SimplyTranslate supports Google TTS, (you can see it here: https://simplytranslate.org) and I would love for this to be implemented in this app as well. There is an api endpoint at /api/tts?engine={engine}&lang={lang}&text={text}

**Comment by Valdnet** [comment]
Steps:

1. Enter the text to be translated.
2. Translate.
3. Delete all translation text by keyboard or text editing toolbar.

The "Speaker" icon is not gray (inactive).

![obraz](https://user-images.githubusercontent.com/47037905/136343204-51b2bcaf-6e8a-4302-82f2-978d45b50ab7.png)

**Comment by ManeraKai** [comment]
> The "Speaker" icon is not gray (inactive).
Yeah I've noticed and changed this before 2 minutes.

**Comment by ManeraKai** [comment]
Enabled the stop button all the time even if there is not text too.

**Comment by ManeraKai** [comment]
Added a notification when the user tries to click the disabled `tts` button. Extracted a string for translation from it too.

**Comment by Valdnet** [comment]
I noticed that the instance in the application settings is now set to "Random". As a result, if the application uses the `st.alefvanoon.xyz` instance, TTS does not work properly due to the lack of implementation on the server.

The user is confused that TTS is working correctly once (if using `simplytranslate.org`) and once it is not working (if using `st.alefvanoon.xyz`). The user has no information that if he uses random choice, or from `st.alefvanoon.xyz`, he cannot use the TTS.

I suggest:
- Go back to setting the default instance on `simplytranslate.org`.

If there are no plans to implement TTS in the `st.alefvanoon.xyz` instance, I suggest:

To set the default instance of `st.alefvanoon.xyz`:

- Inform the user when using TTS (tap on the "Speaker" icon) that he is using an instance that does not support TTS and that if he wants to use TTS he can change to another one in the application settings.

To set the default instance to "Random":

- Inform the user when using TTS (tap on the "Speaker" icon) that he is using a **random** instance that does not support TTS and that if he wants to use TTS he can change to another one in the application settings.

Currently, it only gets the message "Something went wrong".

And it would be best to implement TTS quickly on the server for `st.alefvanoon.xyz`.

**Comment by ManeraKai** [comment]
One minute, can you disable TTS in the `conf` file?

**Comment by Valdnet** [comment]
> change in what way?

To make it more user-friendly. Some new style of the website (interesting colors 😁). Now users like it colorful and pretty. Do not be offended, but this look is no longer fashionable anymore 😉.

BTW: And I invite you to translate the  Simply Translate Mobile app into German. Is he your native language?

**Comment by metalune1** [comment]
I see, well, I'd be happy to see your redesign of it :) also, sure thing I can translate the app to german, just show me how and where and I'll get on it on monday

**Comment by metalune1** [comment]
> I think you could make a normal website with subpages with a nice theme ready. You can implement your code on the main page, add colors, etc.
but what would we use the subpages for? (we're already working on a preferences page) but I don't see how adding extra complexity is going to make it any more appealing, I do understand though that "modernifying" the CSS can make it more appealing

**Comment by Valdnet** [comment]
> but what would we use the subpages for?

You can use for this: Contact, Terms of use, License etc.

The menu can be shaped like graphic buttons, it doesn't have to be text. Something like google that has as: History, Saved, Help. Users like nice graphics. See what is happening with computer systems, programs and see what happened with the Simply Translate Mobile app 😁.

But, that's just my opinion 😉.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1323197560

**Comment by ManeraKai** [comment]
Sorry: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1324063014

**Comment by Valdnet** [comment]
But the error is because if you **quickly** tap the "Speaker" icon several times. In my opinion, it should be blocked from tapping the "Speaker" icon until the message appears.

Normally if TTS is running it is possible to stop speech. In the absence of TTS support by the instances, it is possible to tap several times, which causes the message to appear several times. See the application screen is black, caused by the pop-up of multiple message boxes.

**Comment by ManeraKai** [comment]
Oh sorry, I misunderstood.

**Comment by ManeraKai** [comment]
This solution will be temporary until we get tts support info end point from the server-side: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1324175441

**Comment by ManeraKai** [comment]
Fixed it: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1324293345

**Comment by Valdnet** [comment]
Testing successful 👍.

**Comment by alefvanoon** [comment]
> Yeah because the instance selection is random. I've sent an email to @alefvanoon on Thursday, and a message on Matrix this day. and I'm waiting for his response. We'll try to add a skip logic if he didn't respond in those 2 coming days.

Sorry for being late.

My instance was updated

**Comment by ManeraKai** [comment]
Great! Thanks!

**Comment by ManeraKai** [comment]
> Problem now is if the http request took a long time, you don't have a cancel button.

I think by natural the user will try to click on the loading circle to cancel it. I'm making the loading circle clickable and it's function is to cancel the request.

**Comment by ManeraKai** [comment]
>  I'm making the loading circle clickable and it's function is to cancel the request.

Added that: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1325424181

**Comment by Valdnet** [comment]
Now TTS works fine 🥇.

**Comment by ManeraKai** [comment]
So, this issue will be closed and the end-point's tts support page feature will be opened in another issue for milestone `1.1.3`.

**Comment by ManeraKai** [comment]
It is in `1.1.2`. Just the tts support page on server side will be for `1.1.3`.
I mean this comment: https://github.com/ManeraKai/simplytranslate_mobile/issues/88#issuecomment-938438895

**Comment by ManeraKai** [comment]
That decision will be for the **Simple Web** team. If they created that page. We'll support it, and vise versa 👍
